global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets:
        - 'kafka-1:7071'
        - 'kafka-2:7072'
        - 'kafka-3:7073'
        labels:
          service: 'kafka'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']