global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets:
        - 'kafka-1:9992'
        - 'kafka-2:9993'
        - 'kafka-3:9994'
        labels:
          service: 'kafka'

  - job_name: 'kafka-connect'
    static_configs:
      - targets:
        - 'kafka-connect:8083'
        labels:
          service: 'kafka-connect'

  - job_name: 'ksqldb'
    static_configs:
      - targets:
        - 'ksqldb-server:8088'
        labels:
          service: 'ksqldb'

  - job_name: 'schema-registry'
    static_configs:
      - targets:
        - 'schema-registry:8081'
        labels:
          service: 'schema-registry'

  - job_name: 'jmx-exporter'
    static_configs:
      - targets:
        - 'jmx-exporter:5556'
        labels:
          service: 'jmx'